
image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
      secure: ETwFi/CWuohOW6U5TEAAfDojRAte8t49+atSMyn1cGa/32aS3Wjw6FLTSgaqA/41

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 18 x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build_script:
  - npm run dist

test: off
matrix:
  fast_finish: true
version: '{build}'
shallow_clone: true
